version: "3.8"
   
services:
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/postgres_data
    environment:
      - PGDATA=/var/postgres_data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration

volumes:
  postgres_data: